import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier';

/** @type {import('eslint').Linter.Config[]} */
const config = [
  {
    ignores: [
      '.next/**',
      'out/**',
      'node_modules/**',
      'next-env.d.ts',
      // Generated by scripts/build-worker.mjs; not ours to lint.
      'public/recast-worker/**',
      // Binary and generated fixtures.
      'test/fixtures/**',
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  // Prettier owns formatting; the linter stays out of it.
  prettier,
];

export default config;
